version: '3.8'

services:
  web:
    build: 
      context: .
      args:
        # Pass the variable during the build phase
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
    container_name: nexus-store-web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nexus-commerce
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
    depends_on:
      - db
    command: >
      sh -c "npx prisma db push && npx prisma db seed && npm start"

  
  db:
    image: postgres:16-alpine
    container_name: nexus-store-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus-commerce
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dobm3xsee
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 